[server]
# Optimized for Python 3.12.5 deployment
maxUploadSize = 200
maxMessageSize = 200
enableCORS = false
enableXsrfProtection = false
headless = true
port = 8501

[browser]
gatherUsageStats = false
serverAddress = "0.0.0.0"

[theme]
# Professional color scheme
primaryColor = "#FF6B6B"
backgroundColor = "#FFFFFF"
secondaryBackgroundColor = "#F0F2F6"
textColor = "#262730"
font = "sans serif"

[runner]
# Optimized for stability
magicEnabled = false
enforceSerializableSessionState = false

[client]
# Better user experience
toolbarMode = "minimal"
showErrorDetails = true